import type { Plugin } from '../../types/plugin.js'
import type { BotContext } from '../../types/context.js'
import { execFileSync } from 'child_process'
import * as path from 'path'
import * as fs from 'fs'

const EVERNOTE_REPO = process.env.EVERNOTE_REPO || path.join(process.cwd(), '..', 'Evernote')
const POSTS_DIR = path.join(EVERNOTE_REPO, 'src', 'pages', 'posts')
const NOTES_DIR = path.join(EVERNOTE_REPO, 'src', 'pages', 'notes')

interface GeneratedArticle {
  title: string
  slug: string
  content: string
  tags: string[]
}

async function generateArticle(
  topic: string,
  isNote: boolean
): Promise<GeneratedArticle> {
  const apiKey = process.env.ANTHROPIC_API_KEY
  if (!apiKey) {
    throw new Error('ANTHROPIC_API_KEY not set')
  }

  const prompt = isNote
    ? `你是一個技術筆記產生器。根據主題「${topic}」產生一則簡潔的技術筆記（繁體中文）。

筆記要求：
- 標題：一句話，清楚描述技術重點
- 內容：2-3 段，技術性的實作細節或踩坑經驗
- 風格：直接、簡潔，500 字以內
- 用 markdown 格式

請輸出：
TITLE: <標題>
TAGS: <標籤1>, <標籤2>, <標籤3>
CONTENT:
<內容>`
    : `你是一個技術部落格寫手。根據主題「${topic}」寫一篇技術文章（繁體中文）。

文章要求：
- 標題要有意思，不要太直白（例如：「用 dir 看資料夾的日子結束了」而不是「Yazi 教學」）
- 開頭要有個人經歷和痛點
- 內容要有技術細節
- 語氣輕鬆、有人味（可以用「我」「很煩」「受夠了」）
- 長度 1000-1500 字
- 用 markdown 格式

請輸出：
TITLE: <標題>
TAGS: <標籤1>, <標籤2>, <標籤3>
CONTENT:
<內容>`

  const response = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': apiKey,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 3000,
      messages: [{ role: 'user', content: prompt }],
    }),
    signal: AbortSignal.timeout(60_000),
  })

  if (!response.ok) {
    const error = await response.text()
    throw new Error(`Claude API error: ${response.status} ${error}`)
  }

  const data = (await response.json()) as { content: readonly { text: string }[] }
  const text = data.content[0].text

  const titleMatch = text.match(/TITLE:\s*(.+)/)
  const tagsMatch = text.match(/TAGS:\s*(.+)/)
  const contentMatch = text.match(/CONTENT:\s*([\s\S]+)/)

  if (!titleMatch || !contentMatch) {
    throw new Error('Failed to parse AI response')
  }

  const title = titleMatch[1].trim()
  const tags = tagsMatch
    ? tagsMatch[1]
        .split(',')
        .map((t: string) => t.trim())
        .filter(Boolean)
    : []
  const content = contentMatch[1].trim()

  // Generate slug
  const slug = generateSlug(title)

  return { title, slug, content, tags }
}

function generateSlug(title: string): string {
  // Extract English words
  const englishWords = title.match(/[a-zA-Z]+/g)
  if (englishWords && englishWords.length >= 2) {
    return englishWords
      .slice(0, 4)
      .join('-')
      .toLowerCase()
      .replace(/[^a-z0-9-]/g, '')
  }

  // Fallback: random slug
  return `article-${Date.now().toString(36)}`
}

function writeArticle(article: GeneratedArticle, isNote: boolean): string {
  const now = new Date()
  const dateStr = now.toISOString().slice(0, 16) // YYYY-MM-DDTHH:mm
  const datePrefix = now.toISOString().slice(0, 10) // YYYY-MM-DD

  const layout = isNote
    ? '../../layouts/NoteLayout.astro'
    : '../../layouts/PostLayout.astro'

  const frontmatter = isNote
    ? `---
layout: ${layout}
title: ${article.title}
date: ${dateStr}
${article.tags.length > 0 ? `tags:\n${article.tags.map((t) => `  - ${t}`).join('\n')}` : ''}
source: ClaudeBot
autoGenerated: true
---

${article.content}
`
    : `---
layout: ${layout}
title: ${article.title}
date: ${dateStr}
description: ${article.content.split('\n\n')[0].slice(0, 100)}
${article.tags.length > 0 ? `tags:\n${article.tags.map((t) => `  - ${t}`).join('\n')}` : ''}
---

${article.content}
`

  const targetDir = isNote ? NOTES_DIR : POSTS_DIR
  const filename = `${datePrefix}-${article.slug}.md`
  const filepath = path.join(targetDir, filename)

  // Check collision
  if (fs.existsSync(filepath)) {
    const hash = Math.random().toString(36).slice(2, 6)
    const newFilename = `${datePrefix}-${article.slug}-${hash}.md`
    const newFilepath = path.join(targetDir, newFilename)
    fs.writeFileSync(newFilepath, frontmatter, 'utf-8')
    return newFilename
  }

  fs.writeFileSync(filepath, frontmatter, 'utf-8')
  return filename
}

function commitAndPush(filename: string, isNote: boolean): void {
  const prefix = isNote ? 'note' : 'feat'
  const type = isNote ? 'note' : 'article'

  try {
    execFileSync('git', ['add', filename], { cwd: isNote ? NOTES_DIR : POSTS_DIR, windowsHide: true })
    execFileSync('git', ['commit', '-m', `${prefix}: add ${type} - ${path.basename(filename, '.md')}`], {
      cwd: EVERNOTE_REPO, windowsHide: true,
    })
    execFileSync('git', ['push'], { cwd: EVERNOTE_REPO, windowsHide: true })
  } catch (err) {
    throw new Error(`Git operation failed: ${err instanceof Error ? err.message : 'unknown'}`)
  }
}

async function writeCommand(ctx: BotContext): Promise<void> {
  const text = (ctx.message && 'text' in ctx.message) ? ctx.message.text : ''
  const topic = text.replace(/^\/write\s+/, '').trim()

  if (!topic) {
    await ctx.reply('用法：/write <主題>\n例如：/write React useEffect 清理函數踩坑')
    return
  }

  await ctx.reply('🤖 正在生成文章...')

  try {
    const article = await generateArticle(topic, false)

    // Show preview
    const preview = `📝 **預覽**

**標題：** ${article.title}
**標籤：** ${article.tags.join(', ')}
**字數：** ${article.content.length}

${article.content.slice(0, 300)}...

是否發布？`

    await ctx.reply(preview, {
      parse_mode: 'Markdown',
      reply_markup: {
        inline_keyboard: [
          [
            { text: '✅ 發布', callback_data: `write:publish:${article.slug}` },
            { text: '❌ 取消', callback_data: 'write:cancel' },
          ],
        ],
      },
    })

    // Store article in temp (for callback)
    const tempPath = path.join(EVERNOTE_REPO, '.write-temp.json')
    fs.writeFileSync(tempPath, JSON.stringify(article), 'utf-8')
  } catch (err) {
    const msg = err instanceof Error ? err.message : '未知錯誤'
    await ctx.reply(`❌ 生成失敗：${msg}`)
  }
}

async function writeNoteCommand(ctx: BotContext): Promise<void> {
  const text = (ctx.message && 'text' in ctx.message) ? ctx.message.text : ''
  const topic = text.replace(/^\/write-note\s+/, '').trim()

  if (!topic) {
    await ctx.reply('用法：/write-note <主題>\n例如：/write-note Electron IPC timeout 問題')
    return
  }

  await ctx.reply('🤖 正在生成筆記...')

  try {
    const article = await generateArticle(topic, true)
    const filename = writeArticle(article, true)

    await ctx.reply(`✅ 筆記已生成：${filename}

是否 commit 並 push？`, {
      reply_markup: {
        inline_keyboard: [
          [
            { text: '✅ Commit & Push', callback_data: `write:commit:${filename}` },
            { text: '❌ 不用', callback_data: 'write:skip' },
          ],
        ],
      },
    })
  } catch (err) {
    const msg = err instanceof Error ? err.message : '未知錯誤'
    await ctx.reply(`❌ 生成失敗：${msg}`)
  }
}

async function handleCallback(ctx: BotContext, data: string): Promise<boolean> {
  if (!data.startsWith('write:')) return false

  const [, action, param] = data.split(':')

  if (action === 'publish') {
    try {
      const tempPath = path.join(EVERNOTE_REPO, '.write-temp.json')
      if (!fs.existsSync(tempPath)) {
        await ctx.answerCbQuery('❌ 文章已過期，請重新生成')
        return true
      }

      const article = JSON.parse(fs.readFileSync(tempPath, 'utf-8')) as GeneratedArticle
      const filename = writeArticle(article, false)
      commitAndPush(filename, false)

      fs.unlinkSync(tempPath) // Clean up

      await ctx.answerCbQuery('✅ 已發布')
      await ctx.editMessageText(`✅ 文章已發布並 push：${filename}`)
    } catch (err) {
      const msg = err instanceof Error ? err.message : '未知錯誤'
      await ctx.answerCbQuery(`❌ 發布失敗：${msg}`)
    }
    return true
  }

  if (action === 'cancel') {
    const tempPath = path.join(EVERNOTE_REPO, '.write-temp.json')
    if (fs.existsSync(tempPath)) fs.unlinkSync(tempPath)
    await ctx.answerCbQuery('已取消')
    await ctx.editMessageText('❌ 已取消')
    return true
  }

  if (action === 'commit') {
    try {
      commitAndPush(param, true)
      await ctx.answerCbQuery('✅ 已 push')
      await ctx.editMessageText(`✅ 筆記已 commit 並 push：${param}`)
    } catch (err) {
      const msg = err instanceof Error ? err.message : '未知錯誤'
      await ctx.answerCbQuery(`❌ Push 失敗：${msg}`)
    }
    return true
  }

  if (action === 'skip') {
    await ctx.answerCbQuery('跳過')
    await ctx.editMessageText('✅ 筆記已生成（未 commit）')
    return true
  }

  return false
}

const writePlugin: Plugin = {
  name: 'write',
  description: 'AI 文章產生器',
  commands: [
    {
      name: 'write',
      description: '生成正式文章 (posts/)',
      handler: writeCommand,
    },
    {
      name: 'write-note',
      description: '生成技術筆記 (notes/)',
      handler: writeNoteCommand,
    },
  ],
  onCallback: handleCallback,
}

export default writePlugin
